// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMgr.Data;

#nullable disable

namespace ProMgr.Migrations
{
    [DbContext(typeof(MonumentContext))]
    partial class MonumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("ProMgr.Models.Epic", b =>
                {
                    b.Property<int>("EpicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Misc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EpicId");

                    b.HasIndex("MonumentId");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("ProMgr.Models.Monument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Misc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectManager")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monuments");
                });

            modelBuilder.Entity("ProMgr.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Misc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responisble")
                        .HasColumnType("TEXT");

                    b.HasKey("StoryId");

                    b.HasIndex("EpicId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("ProMgr.Models.Epic", b =>
                {
                    b.HasOne("ProMgr.Models.Monument", "Monument")
                        .WithMany("Epics")
                        .HasForeignKey("MonumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monument");
                });

            modelBuilder.Entity("ProMgr.Models.Story", b =>
                {
                    b.HasOne("ProMgr.Models.Epic", "Epic")
                        .WithMany("Stories")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("ProMgr.Models.Epic", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("ProMgr.Models.Monument", b =>
                {
                    b.Navigation("Epics");
                });
#pragma warning restore 612, 618
        }
    }
}
